import ID from '../assets/icon/flag_id_round.svg'
import EN from '../assets/icon/flag_en_round.svg'
import CN from '../assets/icon/flag_rrt_round.svg'

export var ind = {
    flag: ID,
    flagName: "ID",
    detailAkun: "Detail Akun",
    topUpSaldo: "Top Up Saldo",
    riwayatTopUp: "Riwayat Top Up",
    saldoTersedia: "Saldo Tersedia: ",
    laporan: "Laporan",
    danaMasuk: "Dana Masuk",
    namaAgen: "Nama Agen",
    placeholderNamaAgen: "Pilih Nama Agen",
    status: "Status",
    placeholderStatus: "Pilih Status",
    berhasil: "Berhasil",
    dalamProses: "Dalam Proses",
    gagal: "Gagal",
    menungguPembayaran: "Menunggu Pembayaran",
    kadaluwarsa: "Kadaluwarsa",
    riwayatDisburse: "Riwayat Disbursement",
    filter: "Filter",
    idTransaksi: "ID Transaksi",
    placeholderIdTrans: "Masukan ID Transaksi",
    periode: "Periode",
    pilihPeriode: "Pilih Periode",
    hariIni: "Hari Ini",
    kemarin: "Kemarin",
    tujuhHariTerakhir: "7 Hari Terakhir",
    bulanIni: "Bulan Ini",
    bulanKemarin: "Bulan Kemarin",
    pilihRangeTanggal: "Pilih Range Tanggal",
    jenisTransaksi: "Jenis Transaksi",
    placeholderJenisTransaksi: "Pilih Jenis Transaksi",
    paymentLink: "Payment Link",
    virtualAccount: "Virtual Account",
    namaBank: "Nama Bank",
    placeholderNamaBank: "Pilih Nama Bank",
    partnerTransId: "Trans ID Partner",
    placeholderPartnerTransId: "Masukkan Partner Trans ID",
    terapkan: "Terapkan",
    aturUlang: "Atur Ulang",
    no: "No",
    waktu: "Waktu",
    nominalTransaksi: "Nominal Transaksi",
    biaya: "Biaya",
    nominalDisburse: "Nominal Disbursement",
    totalDisburse: "Total Disbursement",
    tujuanDisburse: "Tujuan Disbursement",
    cabang: "Cabang",
    nomorRekTujuan: "Nomor Rekening Tujuan",
    namaPemilikRek: "Nama Pemilik Rekening",
    catatan: "Catatan",
    totalSettlement: "Total Settlement",
    tidakAdaData: "Tidak ada data",
    riwayat: "Riwayat",
    collectionEwallet: "Collection E-Wallet",
    channel: "Channel",
    channelEwallet: "Channel eWallet",
    directDebit: "Direct Debit",
    namaUser: "Nama User",
    placeholderNamaUser: "Pilih Nama User",
    noHandphone: "No Handphone",
    infoSaldoDanMutasi: "Info Saldo & Mutasi",
    pilihAkun: "Pilih Akun",
    saldoRekSubAkun: "Saldo Rekening Sub Akun",
    klikUntukLihatSaldo: "Klik Untuk Lihat Saldo",
    noRekSubAkun: "No Rekening Sub Account",
    atasNama: "a.n.",
    mutasiRekSubAkun: "Mutasi Rekening Sub Akun",
    idRefBank: "ID Referensi Bank",
    placeholderIdRefBank: "Masukkan ID Referensi",
    idRefTrans: "ID Referensi Transaksi",
    placeholderIdRefTrans: "Masukkan ID Referensi Transaksi",
    rekTujuan: "Rekening Tujuan",
    nominal: "Nominal",
    deskripsi: "Deskripsi",
    keterangan: "Keterangan",
    disbursement: "Disbursement",
    disbursementManual: "Disbursement Manual",
    disbursementBulk: "Disbursement Bulk",
    descManualDisburse: "Pastikan data tujuan Disbursement sudah benar, Ezeelink tidak bertanggung jawab atas kesalahan data yang dilakukan.",
    pilihBankTujuan: "Pilih Bank Tujuan",
    pilihBank: "Pilih Bank",
    descBankTujuan: "Transfer setelah jam 12 siang untuk bank tujuan selain BCA berpotensi diterima di hari berikutnya",
    placeholderCabangBank: "Masukkan Cabang Bank",
    noRekTujuan: "No. Rekening Tujuan",
    placeholderNoRekTujuan: "Masukkan No. Rekening Tujuan",
    placeholderNamaPemilikRek: "Masukkan Nama Pemilik Rekening",
    simpanKeDaftarRek: "Simpan ke Daftar Rekening",
    lihatDaftarRek: "Lihat Daftar Rekening",
    daftarRekening: "Daftar Rekening",
    bankTujuan: "Bank Tujuan",
    noRek: "No Rekening",
    cariDaftarBank: "Cari Data Bank",
    placeholderNamaKodeBank: "Masukkan Nama / Kode Bank",
    batal: "Batal",
    descNominalDisburse: "Nominal Disbursement tidak boleh mengandung Decimal",
    descPilihTujuanBank: "Silahkan pilih tujuan bank terlebih dahulu",
    descMinimalDisburse: "Minimal disbursement",
    emailPenerima: "Email Penerima",
    placeholderEmailPenerima: "Masukkan Alamat Email Penerima",
    placeholderCatatan: "Masukan Catatan Bila Perlu (Maksimal 25 karakter)",
    tambahTujuanDisburse: "Tambah Tujuan Disbursement",
    simpan: "Simpan",
    aksi: "Aksi",
    belumAdaDataDisburse: "Belum ada data tujuan Disbursement",
    ringkasan: "Ringkasan",
    totalFeeDisbursePlusTax: "Total Fee Disbursement + Total Tax",
    totalDisbursePlusFee: "Total Disbursement + Total Fee",
    sisaSaldoTersedia: "Sisa Saldo Tersedia",
    descTerhitung: "(Terhitung setelah seluruh disbursement berhasil)",
    lakukanDisburse: "Lakukan Disbursement",
    daftarBank: "Daftar Bank",
    placeholderDaftarBank: "Masukkan Nama / Kode Bank",
    kodeBank: "Kode Bank",
    descSubDisburseBulk: "Perhatikan panduan pengisian template untuk menghindari kesalahan:",
    lihatPanduan: "Lihat Panduan",
    unduhTemplate: "Unduh Template",
    letakkanFile: "Pilih atau letakan file Excel kamu di sini. <br/> Pastikan file Excel sudah benar, file yang sudah di-upload dan di-disburse tidak bisa kamu batalkan.",
    unggahFile: "Uanggah File",
    kontenTidakSesuai: "Konten pada tabel tidak sesuai dengan template Disbursement Bulk <br/> Ezeelink. Harap download dan menggunakan template yang disediakan <br/> untuk mempermudah pengecekkan data disbursement",
    gantiFile: "Ganti File",
    formatFileExcel: "File yang digunakan harus berformat Excel",
    seluruhDataBankTidakTersedia: "Seluruh data Bank Tujuan tidak tersedia pada saat ini"
}

export var eng = {
    flag: EN,
    flagName: "EN",
    detailAkun: "Account Detail",
    topUpSaldo: "Balance Top Up",
    riwayatTopUp: "Top Up History",
    saldoTersedia: "Available Balance : ",
    laporan: "Report",
    danaMasuk: "Cash In",
    namaAgen: "Agent Name",
    placeholderNamaAgen: "Choose Agent Name",
    status: "Status",
    placeholderStatus: "Choose Status",
    berhasil: "Success",
    dalamProses: "In Process",
    gagal: "Failed",
    menungguPembayaran: "Waiting for Payment",
    kadaluwarsa: "Expired",
    riwayatDisburse: "Disbursement Report",
    filter: "Filter",
    idTransaksi: "Transaction ID",
    placeholderIdTrans: "Enter Transaction ID",
    periode: "Period",
    pilihPeriode: "Choose Period",
    hariIni: "Today",
    kemarin: "Yesterday",
    tujuhHariTerakhir: "Last 7 Days",
    bulanIni: "This Month",
    bulanKemarin: "Last Month",
    pilihRangeTanggal: "Choose Date Range",
    jenisTransaksi: "Transaction Type",
    placeholderJenisTransaksi: "Choose Transaction Type",
    paymentLink: "Payment Link",
    virtualAccount: "Virtual Account",
    namaBank: "Bank Name",
    placeholderNamaBank: "Choose Bank Name",
    partnerTransId: "Partner Trans ID",
    placeholderPartnerTransId: "Enter Partner Trans ID",
    terapkan: "Apply",
    aturUlang: "Reset",
    no: "No",
    waktu: "Transaction Time",
    nominalTransaksi: "Transaction Amount",
    biaya: "Fee",
    nominalDisburse: "Disbursement Amount",
    totalDisburse: "Disbursement Total",
    tujuanDisburse: "Destination Bank",
    cabang: "Branch",
    nomorRekTujuan: "Beneficiary Account Number",
    namaPemilikRek: "Beneficiary Account Name",
    catatan: "Notes",
    totalSettlement: "Settlement Amount",
    tidakAdaData: "There are no record to display",
    riwayat: "History",
    collectionEwallet: "E-Wallet Collection",
    channel: "Channel",
    channelEwallet: "Choose eWallet Channel",
    directDebit: "Direct Debit",
    namaUser: "User name",
    placeholderNamaUser: "Choose User name",
    noHandphone: "Phone Number",
    infoSaldoDanMutasi: "Balance & Mutation Report",
    pilihAkun: "Choose Account",
    saldoRekSubAkun: "Sub Account Balance",
    klikUntukLihatSaldo: "Click to View Balance",
    noRekSubAkun: "Sub Account - Account Number",
    atasNama: "p.p.",
    mutasiRekSubAkun: "Sub Account Mutation Report",
    idRefBank: "Bank Reference ID",
    placeholderIdRefBank: "Enter Reference ID",
    idRefTrans: "Transaction Reference ID",
    placeholderIdRefTrans: "Enter Transaction Reference ID",
    rekTujuan: "Destination Bank",
    nominal: "Amount",
    deskripsi: "Description",
    keterangan: "Information",
    disbursement: "Disbursement",
    disbursementManual: "Manual Disbursement",
    disbursementBulk: "Bulk Disbursement",
    descManualDisburse: "Make sure the Disbursement destination data is correct, Ezeelink is not responsible for data errors made.",
    pilihBankTujuan: "Choose Destination Bank",
    pilihBank: "Choose Bank",
    descBankTujuan: "Transfers after 12 pm to banks other BCA have the potential to be received in the next day",
    placeholderCabangBank: "Input Branch",
    noRekTujuan: "Beneficiary Account Number",
    placeholderNoRekTujuan: "Input Beneficiary Account Number",
    placeholderNamaPemilikRek: "Input Beneficiary Account Name",
    simpanKeDaftarRek: "Save to Account List",
    lihatDaftarRek: "View Account List",
    daftarRekening: "Account List",
    bankTujuan: "Destination Bank",
    noRek: "Account Number",
    cariDaftarBank: "Search Bank",
    placeholderNamaKodeBank: "Input Bank Name/Bank Code",
    batal: "Cancel",
    descNominalDisburse: "Amount of disbursement shouldn't contain decimal",
    descPilihTujuanBank: "Please select the destination bank first",
    descMinimalDisburse: "Minimum of Disbursement is",
    emailPenerima: "Beneficiarry Email",
    placeholderEmailPenerima: "Input Beneficiary Email Address",
    placeholderCatatan: "Input Note If Needed (Max. 25 character)",
    tambahTujuanDisburse: "Add Disbursement",
    simpan: "Save",
    aksi: "Action",
    belumAdaDataDisburse: "There is no data yet",
    ringkasan: "Summary",
    totalFeeDisbursePlusTax: "Total of Fee Disbursement + Total Tax",
    totalDisbursePlusFee: "Total of Disbursement + Total Fees",
    sisaSaldoTersedia: "Remaining Balance",
    descTerhitung: "(Calculated after disbursement completed)",
    lakukanDisburse: "Submit Disbursement",
    daftarBank: "Bank List",
    placeholderDaftarBank: "Input Bank Name / Bank Code",
    kodeBank: "Bank Code",
    descSubDisburseBulk: "Please view the template filling guide to avoid mistakes:",
    lihatPanduan: "See Guides",
    unduhTemplate: "Download Template",
    letakkanFile: "Select or drop your Excel file here. <br/> Make sure the Excel file is correct, you can't cancel files that have been uploaded and disbursed.",
    unggahFile: "Upload File",
    kontenTidakSesuai: "The content in the table does not match the Ezeelink Bulk <br/> Disbursement template. Please download and use the template provided <br/> to make it easier to check disbursement data",
    gantiFile: "Change File",
    formatFileExcel: "The file must be in Excel format",
    seluruhDataBankTidakTersedia: "All Destination Bank is not available right now"
}

export var chn = {
    flag: CN,
    flagName: "CN",
    detailAkun: "账户详情",
    topUpSaldo: "余额充值",
    riwayatTopUp: "充值历史",
    saldoTersedia: "可用余额：",
    laporan: "报告",
    danaMasuk: "兑现",
    namaAgen: "代理名",
    placeholderNamaAgen: "代理名字",
    status: "状态",
    placeholderStatus: "选择状态",
    berhasil: "成功",
    dalamProses: "正在办理",
    gagal: "无效",
    menungguPembayaran: "等待付款",
    kadaluwarsa: "过期",
    riwayatDisburse: "支付报告",
    filter: "帅选",
    idTransaksi: "交易ID",
    placeholderIdTrans: "交易ID",
    periode: "周期",
    pilihPeriode: "选择日期",
    hariIni: "今天",
    kemarin: "昨天",
    tujuhHariTerakhir: "前 7 天",
    bulanIni: "这个月",
    bulanKemarin: "上个月",
    pilihRangeTanggal: "选择日期范围",
    jenisTransaksi: "交易类型",
    placeholderJenisTransaksi: "选择交易类别",
    paymentLink: "付款链接",
    virtualAccount: "Virtual Account",
    namaBank: "银行名",
    placeholderNamaBank: "选择银行名",
    partnerTransId: "合作伙伴交易ID",
    placeholderPartnerTransId: "输入合作伙伴交易ID",
    terapkan: "申请",
    aturUlang: "重置",
    no: "编号",
    waktu: "交易时间",
    nominalTransaksi: "交易额度",
    biaya: "费用",
    nominalDisburse: "支付额度",
    totalDisburse: "支付总额",
    tujuanDisburse: "目标银行",
    cabang: "分支",
    nomorRekTujuan: "收款人账号",
    namaPemilikRek: "收款人账户名称",
    catatan: "注释",
    totalSettlement: "结算额度",
    tidakAdaData: "无数据可显示",
    riwayat: "Riwayat",
    collectionEwallet: "电子钱包集合",
    channel: "渠道",
    channelEwallet: "选择电子钱包渠道",
    directDebit: "直接借记",
    namaUser: "用户名",
    placeholderNamaUser: "选择用户名",
    noHandphone: "电话号码",
    infoSaldoDanMutasi: "余额信息和转账记录",
    pilihAkun: "选择账户",
    saldoRekSubAkun: "子账户余额",
    klikUntukLihatSaldo: "点击查看余额",
    noRekSubAkun: "子账户 - 账号",
    atasNama: "p.p.",
    mutasiRekSubAkun: "子账户转账记录",
    idRefBank: "银行参考ID",
    placeholderIdRefBank: "输入参考ID",
    idRefTrans: "交易参考ID",
    placeholderIdRefTrans: "输入交易参考ID",
    rekTujuan: "目标银行",
    nominal: "额度",
    deskripsi: "描述",
    keterangan: "明细",
    disbursement: "支出",
    disbursementManual: "手动付款",
    disbursementBulk: "批量支付",
    descManualDisburse: "请确保付款目的地数据正确，Ezeelink 对数据错误不承担任何责任。",
    pilihBankTujuan: "选择目标银行",
    pilihBank: "选择银行",
    descBankTujuan: "中午 12 点后转账至除 BCA 银行意外可能会在第二天才收到转账",
    placeholderCabangBank: "输入分支",
    noRekTujuan: "收款人账号",
    placeholderNoRekTujuan: "输入收款人账号",
    placeholderNamaPemilikRek: "输入收款人账户名称",
    simpanKeDaftarRek: "保存到账号列表",
    lihatDaftarRek: "查看账户列表",
    daftarRekening: "账户列表",
    bankTujuan: "目标银行",
    noRek: "账号",
    cariDaftarBank: "搜索银行",
    placeholderNamaKodeBank: "输入银行名称/银行代码",
    batal: "取消",
    descNominalDisburse: "支付金额不能包含小数",
    descPilihTujuanBank: "请先选择目标银行",
    descMinimalDisburse: "最低付款额为",
    emailPenerima: "收款人电子邮件",
    placeholderEmailPenerima: "输入收款人电子邮件地址",
    placeholderCatatan: "如果需要，请输入注释（最多 25 个字符）",
    tambahTujuanDisburse: "添加支出",
    simpan: "Save",
    aksi: "动态",
    belumAdaDataDisburse: "还没有数据",
    ringkasan: "概括",
    totalFeeDisbursePlusTax: "费用支付总额 + 税金总额",
    totalDisbursePlusFee: "支出总额 + 费用总额",
    sisaSaldoTersedia: "剩余余额",
    descTerhitung: "(支付完成后计算)",
    lakukanDisburse: "提交付款",
    daftarBank: "银行名单",
    placeholderDaftarBank: "输入银行名称/银行代码",
    kodeBank: "银行代码",
    descSubDisburseBulk: "请查看模板填写指南以避免错误：",
    lihatPanduan: "查看指南",
    unduhTemplate: "下载模板",
    letakkanFile: "在此处选择或放置您的 Excel 文件。<br/> 确保Excel文件正确，已上传和支付的文件无法取消。",
    unggahFile: "上传文件",
    kontenTidakSesuai: "表中的内容与 Ezeelink 批量付款模板不匹配。 请下载并使用提供的模板，以便查看付款数据",
    gantiFile: "更改文件",
    formatFileExcel: "文件必须是 Excel 格式",
    seluruhDataBankTidakTersedia: "目前无法使用所有目标银行"
}