import ID from '../assets/icon/flag_id_round.svg'
import EN from '../assets/icon/flag_en_round.svg'
import CN from '../assets/icon/flag_rrt_round.svg'

export var ind = {
    flag: ID,
    flagName: "ID",
    detailAkun: "Detail Akun",
    topUpSaldo: "Top Up Saldo",
    riwayatTopUp: "Riwayat Top Up",
    saldoTersedia: "Saldo Tersedia: ",
    laporan: "Laporan",
    danaMasuk: "Dana Masuk",
    namaAgen: "Nama Agen",
    placeholderNamaAgen: "Pilih Nama Agen",
    status: "Status",
    placeholderStatus: "Pilih Status",
    berhasil: "Berhasil",
    dalamProses: "Dalam Proses",
    gagal: "Gagal",
    menungguPembayaran: "Menunggu Pembayaran",
    kadaluwarsa: "Kadaluwarsa",
    riwayatDisburse: "Riwayat Disbursement",
    filter: "Filter",
    idTransaksi: "ID Transaksi",
    placeholderIdTrans: "Masukkan ID Transaksi",
    periode: "Periode",
    pilihPeriode: "Pilih Periode",
    hariIni: "Hari Ini",
    kemarin: "Kemarin",
    tujuhHariTerakhir: "7 Hari Terakhir",
    bulanIni: "Bulan Ini",
    bulanKemarin: "Bulan Kemarin",
    pilihRangeTanggal: "Pilih Range Tanggal",
    jenisTransaksi: "Jenis Transaksi",
    placeholderJenisTransaksi: "Pilih Jenis Transaksi",
    paymentLink: "Payment Link",
    virtualAccount: "Virtual Account",
    namaBank: "Nama Bank",
    placeholderNamaBank: "Pilih Nama Bank",
    partnerTransId: "Trans ID Partner",
    placeholderPartnerTransId: "Masukkan Partner Trans ID",
    terapkan: "Terapkan",
    aturUlang: "Atur Ulang",
    no: "No",
    waktu: "Waktu Transaksi",
    nominalTransaksi: "Nominal Transaksi",
    biaya: "Biaya",
    nominalDisburse: "Nominal Disbursement",
    totalDisburse: "Total Disbursement",
    tujuanDisburse: "Tujuan Disbursement",
    cabang: "Cabang",
    nomorRekTujuan: "Nomor Rekening Tujuan",
    namaPemilikRek: "Nama Pemilik Rekening",
    catatan: "Catatan",
    totalSettlement: "Total Settlement",
    tidakAdaData: "Tidak ada data",
    riwayat: "Riwayat",
    collectionEwallet: "Collection E-Wallet",
    channel: "Channel",
    channelEwallet: "Channel eWallet",
    directDebit: "Direct Debit",
    namaUser: "Nama User",
    placeholderNamaUser: "Pilih Nama User",
    noHandphone: "No Handphone",
    infoSaldoDanMutasi: "Info Saldo & Mutasi",
    pilihAkun: "Pilih Akun",
    saldoRekSubAkun: "Saldo Rekening Sub Akun",
    klikUntukLihatSaldo: "Klik Untuk Lihat Saldo",
    noRekSubAkun: "No Rekening Sub Account",
    atasNama: "a.n.",
    mutasiRekSubAkun: "Mutasi Rekening Sub Akun",
    idRefBank: "ID Referensi Bank",
    placeholderIdRefBank: "Masukkan ID Referensi",
    idRefTrans: "ID Referensi Transaksi",
    placeholderIdRefTrans: "Masukkan ID Referensi Transaksi",
    rekTujuan: "Rekening Tujuan",
    nominal: "Nominal",
    deskripsi: "Deskripsi",
    keterangan: "Keterangan",
    disbursement: "Disbursement",
    disbursementManual: "Disbursement Manual",
    disbursementBulk: "Disbursement Bulk",
    descManualDisburse: "Pastikan data tujuan Disbursement sudah benar, Ezeelink tidak bertanggung jawab atas kesalahan data yang dilakukan.",
    pilihBankTujuan: "Pilih Bank Tujuan",
    pilihBank: "Pilih Bank",
    descBankTujuan: "Transfer setelah jam 12 siang untuk bank tujuan selain BCA berpotensi diterima di hari berikutnya",
    placeholderCabangBank: "Masukkan Cabang Bank",
    noRekTujuan: "No. Rekening Tujuan",
    placeholderNoRekTujuan: "Masukkan No. Rekening Tujuan",
    placeholderNamaPemilikRek: "Masukkan Nama Pemilik Rekening",
    simpanKeDaftarRek: "Simpan ke Daftar Rekening",
    lihatDaftarRek: "Lihat Daftar Rekening",
    daftarRekening: "Daftar Rekening",
    bankTujuan: "Bank Tujuan",
    noRek: "No Rekening",
    cariDaftarBank: "Cari Data Bank :",
    placeholderNamaKodeBank: "Masukkan Nama / Kode Bank",
    batal: "Batal",
    descNominalDisburse: "Nominal Disbursement tidak boleh mengandung Decimal",
    descPilihTujuanBank: "Silahkan pilih tujuan bank terlebih dahulu",
    descMinimalDisburse: "Minimal disbursement",
    emailPenerima: "Email Penerima",
    placeholderEmailPenerima: "Masukkan Alamat Email Penerima",
    placeholderCatatan: "Masukan Catatan Bila Perlu (Maksimal 25 karakter)",
    tambahTujuanDisburse: "Tambah Tujuan Disbursement",
    simpan: "Simpan",
    aksi: "Aksi",
    belumAdaDataDisburse: "Belum ada data tujuan Disbursement",
    ringkasan: "Ringkasan",
    totalFeeDisbursePlusTax: "Total Fee Disbursement + Total Tax",
    totalDisbursePlusFee: "Total Disbursement + Total Fee",
    sisaSaldoTersedia: "Sisa Saldo Tersedia",
    descTerhitung: "(Terhitung setelah seluruh disbursement berhasil)",
    lakukanDisburse: "Lakukan Disbursement",
    daftarBank: "Daftar Bank",
    placeholderDaftarBank: "Masukkan Nama / Kode Bank",
    kodeBank: "Kode Bank",
    descSubDisburseBulk: "Perhatikan panduan pengisian template untuk menghindari kesalahan:",
    lihatPanduan: "Lihat Panduan",
    unduhTemplate: "Unduh Template",
    letakkanFile: "Pilih atau letakkan file Excel kamu di sini. <br/> Pastikan file Excel sudah benar, file yang sudah di-upload dan di-disburse tidak bisa kamu batalkan.",
    unggahFile: "Uanggah File",
    kontenTidakSesuai: "Konten pada tabel tidak sesuai dengan template Disbursement Bulk <br/> Ezeelink. Harap download dan menggunakan template yang disediakan <br/> untuk mempermudah pengecekkan data disbursement",
    gantiFile: "Ganti File",
    formatFileExcel: "File yang digunakan harus berformat Excel",
    seluruhDataBankTidakTersedia: "Seluruh data Bank Tujuan tidak tersedia pada saat ini",
    riwayatTransaksi: "Riwayat Transaksi",
    riwayatSaldo: "Riwayat Saldo",
    tipeSaldo: "Tipe Saldo",
    placeholderTipeSaldo: "Pilih Tipe Saldo",
    export: "Ekspor",
    totalHalaman: "Total Halaman",
    saldoSebelum: "Saldo Sebelum",
    saldoSesudah: "Saldo Sesudah",
    nominalTopUpSaldo: "Nominal Top Up Saldo",
    rp: "Rp",
    topUp: "TOP UP",
    selesaikanProsesTopUp: "Selesaikan Proses Top Up",
    selesaikanPembayaran: "Selesaikan Pembayaran Dalam",
    batasAkhir: "Batas Akhir ",
    metodePembayaran: "Metode Pembayaran",
    transferBank: "Transfer Bank",
    nominalTransfer: "Nominal Transfer",
    salin: "Salin",
    lakukanTransfer: "Lakukan transfer sesuai dengan nominal yang tertera hingga 3 digit terakhir.",
    sayaSudahTransfer: "SAYA SUDAH TRANSFER",
    tanggal: "Tanggal",
    konfigurasi: "Konfigurasi",
    aktif: "Aktif",
    tidakAktif: "Tidak Aktif",
    idPartner: "ID Partner",
    namaPerusahaan: "Nama Perusahaan",
    emailPerusahaan: "Email Perusahaan",
    noTelp: "Nomor Telepon",
    alamat: "Alamat",
    noNpwp: "No NPWP",
    namaNpwp: "Nama NPWP",
    sumberAgen: "Sumber Agen",
    namaDirektur: "Nama Direktur",
    noHpDirektur: "No Hp Direktur",
    daftarAgen: "Daftar Agen",
    tambahAgen: "Tambah Agen",
    cariNamaAgen: "Cari Nama Agen",
    placeholderCariNamaAgen: "Masukkan Nama Agen",
    idAgen: "ID Agen",
    email: "Email",
    default: "Default",
    kodeUnik: "Kode Unik",
    detailAgen: "Detail Agen",
    emailAgen: "Email Agen",
    noHpAgen: "No Hp Agen",
    silahkanHubungiAdmin: "Silahkan hubungi Admin untuk menambahkan Sub Account pada Agen",
    rekSubAkun: "Rekening Sub Account",
    tambahAgenBaru: "Tambah Agen Baru",
    emailSudahTerdaftar: "Email sudah terdaftar menjadi agen",
    noHpSudahTerdaftar: "No Hp sudah terdaftar menjadi agen",
    biayaSettlement: "Biaya Settlement",
    tambahkan: "Tambahkan",
    agenBerhasilDitambah: "Agen Berhasil Ditambahkan",
    agenSudahAktif: "Agen sudah aktif dan transaksi agen akan tercatat di dashboard Anda",
    idAgenDanKodeUnik: "ID Agen & Kode Unik",
    oke: "Oke",
    membatalkanPerubahanDataPartner: "Apakah kamu yakin ingin membatalkan perubahan yang dilakukan pada data partner?",
    dataKembaliKondisiSemula: "Data akan kembali seperti kondisi semula.",
    menyimpanDataPerubahan: "Apakah Kamu yakin ingin menyimpan perubahan data Partner?",
    perubahanDataBaru: "Perubahan data yang dilakukan akan tersimpan sebagai data baru agen",
    menonaktifkanAgen: "Apakah kamu yakin ingin menonaktifkan agen?",
    transaksiAgenTidakTersimpan: "Transaksi agen tidak akan tersimpan di dashboard",
    aktifkanAgen: "Apakah kamu yakin ingin aktifkan agen?",
    transaksiAgenTersimpan: "Transaksi agen akan tersimpan di dashboard",
    daftarUserDirectDebit: "Daftar User Direct Debit",
    namaPartner: "Nama Partner",
    idUser: "ID User",
    detailIdUser: "Detail ID User",
    descIdUser: "ID User adalah kode unik yang didapat dari Bank berupa kombinasi angka dan alphanumerik serta tidak dapat diubah oleh admin",
    idUserTersalin: "ID User Tersalin",
    buatPaymentLink: "Buat Payment Link",
    paymentId: "ID Pembayaran",
    placeholderPaymentId: "Masukan ID Pembayaran",
    idRef: "ID Referensi",
    placeholderIdRef: "Masukan ID Referensi",
    tanggalPembuatan: "Tanggal Pembuatan",
    settlement: "Settlement",
    ditutup: "Ditutup",
    detail: "Detail",
    minNominalTagihan: "Nominal Tagihan Min. Rp 10.000",
    aturWaktu: "Atur Waktu",
    masaKadaluarsa: "Masa kadaluarsa tidak boleh kurang dari 5 menit",
    batasPemakaian: "Batas Pemakaian",
    catatanBatasPemakaian: "Catatan: Batas Pemakaian adalah seberapa banyak link diatas dapat diakses",
    semuaMetodePembayaran: "Semua Metode Pembayaran",
    aturBeberapa: "Atur Beberapa",
    placeholderDeskripsi: "Masukkan Deskripsi",
    customDesignPaymentLink: "Custom Design Laman Bayar",
    previewTampilan: "Preview Tampilan",
    logoAnda: "Logo Anda",
    namaPerusahaanAnda: "Nama Perusahaan Anda",
    totalPembayaran: "Total Pembayaran",
    nama: "Nama",
    placeholderNama: "Masukkan nama Anda",
    placeholderEmail: "Masukkan email Anda",
    descPreviewTampilan: "Data ini akan kami gunakan untuk mengirim bukti transaksi pembayaran melalui email Anda",
    lanjutkan: "Lanjutkan",
    aturTampilan: "Atur Tampilan",
    logoPerusahaan: "Logo Perusahaan",
    uploadFile: "Unggah File",
    ukuranFileCustom: "Ukuran 2:1. size maks 500kb",
    simpanPerubahan: "Simpan Perubahan?",
    seluruhPerubahanTersimpan: "Seluruh perubahan yang anda buat akan tersimpan dan tampilan laman bayar akan diperbarui",
    seluruhPerubahanTerhapus: "Seluruh perubahan yang anda buat akan terhapus dan tampilan dikembalikan seperti sebelumnya",
    batalkanPerubahan: "Batalkan Perubahan?",
    batalkan: "Batalkan",
    kembali: "Kembali",
    biayaAdmin: "Biaya Admin",
    transaksi: "Transaksi",
    transaksiDirectDebitUser: "Transaksi Direct Debit User",
    channelDirectDebit: "Channel Direct Debit",
    periodeTransaksi: "Periode Transaksi",
    statusTransaksi: "Status Transaksi",
    masukkanKataSandiSub: "Masukan Kata Sandi Login Anda",
    kataSandi: "Kata Sandi",
    placeholderKataSandi: "Masukkan Kata Sandi",
    lihatSaldo: "Lihat Saldo",
    panduanPengisianDisburseBulk: "Panduan Pengisian Disbursement Bulk",
    descPanduanDisburseBulk: "Pastikan data tujuan Disbursement sudah benar, Ezeelink tidak bertanggung jawab atas kesalahan data yang dilakukan, dan tetap akan dikenakan biaya sesuai dengan Fee Disbursement yang ditetapkan.",
    panduan1: "File yang diunggah wajib dalam format excel, dan tidak dapat menggunakan format lain",
    panduan2: "File yang diunggah wajib menggunakan template file yang telah disediakan, tidak bisa membuat format sendiri",
    panduan3: "Dilarang mengubah atau menambahkan nama sheet, nama tabel, urutan tabel dan tipe data tabel. Mengubah nama file diperbolehkan sesuai kebutuhan",
    panduan4: `Wajib Diisi - Bank Tujuan diisi sesuai dengan daftar bank tujuan disbursement dan wajib menyertakan kode bank. Untuk kode bank dengan awalan 0, harus ditulis dengan tanda petik 1 untuk meminimalisir kesalahan pada data excel (Contoh: ’014-BCA)Daftar bank dapat dilihat pada file berikut : `,
    panduan5: "Wajib Diisi khusus cabang tujuan bank selain BCA. Apabila bank yang dipilih adalah BCA maka dapat dikosongkan",
    panduan6: "Wajib Diisi - Nomor Rekening Tujuan diisi sesuai format rekening bank tujuan. Gunakan format angka dan harap perhatikan digit rekening. Untuk nomor rekening dengan angka 0 didepan, harus ditulis dengan tanda petik 1 untuk meminimalisir kesalahan pada data excel (Contoh: ’098765421)",
    panduan7: "Wajib Diisi - Nama Pemilik Rekening wajib diisi dengan benar dan sesuai",
    panduan8: "Wajib Diisi - Nominal Disbursement diisi dalam format Rupiah. Nominal disbursement tidak boleh mengandung decimal",
    panduan9: "Email Penerima bersifat opsional dan dapat diisi untuk mengirim notifikasi berhasil Disburse. Apabila email tidak diisi, maka dapat dikosongkan",
    panduan10: "Catatan dapat diisi bila diperlukan dan bersifat opsional dan maksimal 25 karakter (termasuk spasi).",
    panduan11: "Kolom Cabang, Nama Pemilik Rekening, Email Penerima, dan Catatan wajib ditulis dalam alfabet.",
    daftarBankTujuan: "Daftar Bank Tujuan",
    mengerti: "Mengerti",
    kesalahanDataPerluDiperbaiki: "Kesalahan data yang perlu diperbaiki",
    dataPadaBarisKe: "Data pada baris ke",
    barisKe: "",
    konfirmasiDisburse: "Konfirmasi Disbursement",
    descKonfirmasiDisburse: "Harap pastikan seluruh data disbursement sudah benar. Kesalahan pada data dapat menyebabkan kegagalan disbursement dan tetap akan dikenakan biaya sesuai dengan Fee Disbursement yang ditetapkan.",
    saldoTidakCukup: "Saldo Anda tidak cukup, Topup saldo terlebih dahulu sebelum melakukan disbursement",
    sayaBertanggungJawab: "Saya bertanggung jawab atas seluruh kebenaran maupun kesalahan data di atas",
    silahkanCobaUploadUlang: "Silahkan coba upload ulang beberapa saat lagi. Silahkan hubungi Admin untuk informasi lebih lanjut",
    jumlahSheetPadaFileExcel: "Jumlah Sheet pada file Excel lebih dari 1. Harap tinjau kembali file anda agar sesuai dengan template.",
    dataPadaFileMasihKosong: "Data pada file masih kosong. Harap tinjau kembali data pada file anda.",
    kolomBankTujuanWajibDiisi: "kolom Bank Tujuan : Wajib Diisi.",
    kolomBankTujuanSalah : "kolom Bank Tujuan : Bank Tujuan salah / tidak tersedia pada saat ini.",
    kolomNoRekWajibDiisi: "kolom Nomor Rekening : Wajib Diisi.",
    kolomNoRekTipeDataSalah: "kolom Nomor Rekening : Tipe data salah.",
    kolomNoRekDigitRekTidakSesuai: "kolom Nomor Rekening : Digit nomor rekening tidak sesuai dengan bank tujuan.",
    kolomCabangTidakTersedia: "kolom Cabang : Cabang tidak tersedia",
    kolomCabangWajibDiisi: "kolom Cabang : Wajib Diisi",
    kolomNominalDisburseWajibDiisi: "kolom Nominal Disbursement : Wajib Diisi.",
    kolomNominalDisburseTipeDataSalah: "kolom Nominal Disbursement : Tipe data salah.",
    kolomNominalDisburseMinNominal: "kolom Nominal Disbursement : Minimal Nominal Disbursement",
    kolomNominalDisburseMaksNominal: "kolom Nominal Disbursement : Maksimal Nominal Disbursement",
    kolomNominalDisburseTidakBolehDesimal: "Nominal Disbursement tidak boleh mengandung Decimal",
    saldoAndaTidakCukup: "Saldo anda tidak cukup",
    pilihFile: "Pilih File",
    descSectionOneSub: "Anda perlu mengetahui ",
    partnerId: "ID Partner",
    dan: "dan ",
    descSectionTwoSub: "untuk terkonfigurasi dengan Ezeelink. Silakan gunakan Development Server saat Anda masih dalam tahap pengembangan.",
    thisKeyInKonfigurasi: "Secret Key ini digenerate secara otomatis oleh sistem dan tidak boleh diubah. Jika Anda benar-benar perlu mengubah karena alasan tertentu, silakan hubungi kami",
    hubungiKami: "hubungi kami",
    ezeelinkMemerlukanUrl: "Ezeelink memerlukan endpoint URL untuk skenario berikut:",
    paymentNotifUrl: "URL Notifikasi Pembayaran",
    addressUrl: "URL dimana kami akan mengirimkan notifikasi melalui permintaan HTTP Post. Misalnya http://yourwebsite.com/notification/handing",
    update: "Perbarui",
    mohonTunggu: "Mohon tunggu",
    subAccount: "Sub Account",
    subAccountBank: "Sub Account Bank",
    transfer: "Transfer",
    placeholderNominalTransfer: "Masukkan Nominal Transfer",
    periksa: "Periksa",
    rekeningTerkonfirmasi: "Rekening Terkonfirmasi",
    silahkanPilihBankDahulu: "Silahkan pilih bank terlebih dahulu",
    biayaTransfer: "Biaya Transfer",
    transferSekarang: "Transfer Sekarang",
    konfirmasiTransfer: "Konfirmasi Transfer",
    dariRek: "",
    bank: "Bank",
    total: "Total",
    konfirmasiOtp: "Konfirmasi OTP",
    kodeVerifikasi: "Kode Verifikasi udah dikirim via SMS ke nomor",
    tidakMenerimaOtp: "Tidak menerima kode OTP?",
    kirimUlang: "Kirim Ulang",
    mohonTungguDalam: "Mohon tunggu dalam",
    untukKirimUlang: "untuk kirim ulang",
    maksimumPermintaanOtp: "Maksimum permintaan OTP",
    konfirmasi: "Konfirmasi",
    andaMencapaiMaksPermintaanOtp: "Anda telah mencapai maksimum permintaan OTP pada hari ini!",
    batasMaksimumOtp: "Batas maksimum adalah 3 permintaan OTP  per-hari. Coba lagi dalam 1x24 jam kedepan untuk melakukan permintaan OTP.",
    cekMutasi: "Cek mutasi secara berkala untuk mengetahui status transfer",
    unduhBuktiTf: "Unduh Bukti Transfer",
    lihatMutasi: "Lihat Mutasi",
    show: "Lihat",
    entries: "entries",
    detailPaymentLink: "Detail Payment Link",
    dibuatPada: "Dibuat Pada",
    tanggalKadaluarsa: "Tanggal Kadaluarsa",
    batasPembayaran: "Batas Pembayaran",
    tutupPaymentLink: "Tutup Payment Link",
    placeholderNominalTagihan: "Masukkan Nominal Tagihan",
    biayaAdminPaymentLink: "Biaya Admin: Rp 0 ( Dibebankan kepada partner )",
    catatanIdRef: "Catatan: ID Referensi bisa berupa kata atau digit angka",
    silahkanHubCs: "Silahkan hubungi Customer Service untuk mengatur metode pembayaran",
    selamatPaymentLinkBerhasilDibuat: "Selamat, Payment Link Kamu Berhasil Dibuat",
    linkTersalin: "Link Tersalin",
    salinLink: "Salin Link",
    silahkanSalinLink: "Silahkan salin link diatas untuk menerima pembayaran kamu.",
    tutup: "Tutup",
    yakinInginKeluar: "Apakah Kamu Yakin Ingin Keluar dari Halaman ini?",
    seluruhPerubahan: "Seluruh perubahan yang kamu buat akan terhapus",
    keluar: "Keluar",
    tidak: "Tidak",
    aturMetodePembayaran: "Atur Metode Pembayaran",
    metodePembayaranHarusDipilih :"Metode pembayaran harus dipilih.",
    ya: "Ya",
    edit: "Edit",
    placeholderEmailAgen: "Masukkan Email Agen",
    placeholderNoHpAgen: "Masukkan No Hp Agen",
    placeholderNoRek: "Masukkan No Rekening",
    placeholderSettleFee: "Masukkan Jumlah Settlement Fee",
    dataTidakValid: "Data Tidak Valid",
    maksimalDisburse: "Maksimal disbursement",
    formatEmail: `Format email wajib memakai tanda ‘@’. Contoh: nama@mail.com`,
    kolomNomorRekDigitNomorRek: "kolom Nomor Rekening : Digit nomor rekening tidak sesuai dengan bank tujuan.",
    salinId: "Salin ID",
    cabangKhususNonBca: "Cabang (Khusus Non-BCA)",
    disburseSedangDiproses: "Disbursement Sedang Diproses.",
    lihatRiwayatDisburse: "Lihat Riwayat Disbursement",
    logout: "Keluar",
    harapPerbaikiData: "Harap perbaiki data terlebih dahulu sebelum mengupload ulang file.",
    yakinPindahHalaman: "Yakin ingin pindah halaman?",
    ditemukanDuplikasiData: "Ditemukan Duplikasi Data, Ingin Tetap Melanjutkan?",
    dataInginDitambahkanTelahTersedia: "Data yang ingin Anda tambahkan sudah tersedia di tabel.",
    perbaiki: "Perbaiki",
    kolomNamaPemilikRekWajibDiisi: "kolom Nama Pemilik Rekening : Wajib Diisi.",
    kolomNomorRekTipeDataSalah: "kolom Nomor Rekening : Tipe data salah.",
    kolomEmailPenerimaTipeDataSalah: "kolom Email Penerima : Tipe data salah.",
    kolomCatatanMaksKarakter: "kolom Catatan : Maks 25 karakter.",
    bankTujuanStar: "Bank Tujuan*",
    noRekTujuanStar: "No. Rekening Tujuan*",
    namaPemilikRekStar: "Nama Pemilik Rekening*",
    nominalDisburseStar: "Nominal Disbursement*",
    cabangStar: "Cabang*",
    emailPenerimaStarAlpabet: "Email Penerima",
    catatanStarAlpabet: "Catatan",
    placeholderNamaPerusahaan: "Masukkan nama Perusahaan Anda",
    lihatSemua: "Lihat Semua",
    letakkanFileWithCsv: "Pilih atau letakkan file Excel (*.csv) kamu di sini. <br/> Pastikan file Excel sudah benar, file yang sudah di-upload dan di-disburse tidak bisa kamu batalkan.",
    kataSandiSalah: "Kata Sandi Salah",
    sistemSedangBermasalah: "Sistem Sedang Bermasalah",

    descSistemBermasalah: "Saat ini sistem kami sedang mengalami gangguan sehingga tidak dapat menampilkan saldo anda. Mohon coba beberapa saat lagi",
    saldoRekSubAccount: "Saldo Rekening Sub Account",
    nominalSaldoSaatIni: "Nominal Saldo Saat Ini",
    seluruhDataDiinputAkanTerhapus: "Seluruh data yang telah diinput akan terhapus jika pindah halaman, masih ingin melanjutkan?",
    kembaliKeLoginPage: "Kembali ke Login Page",
    lupaKataSandi: "Lupa Kata Sandi",
    descKataSandi: "Masukan email yang kamu daftarkan dibawah ini dan kami akan mengirim pesan email beserta link untuk reset kata sandi",
    placeholderMasukkanEmail: "Masukkan Email",
    kirimLink: "Kirim Link",
    linkBehasilDikirim: "Link Berhasil Dikirim ke Email",
    periksaEmailDanIkutiInstruksi: "Silahkan periksa email dan ikuti intruksi untuk mereset kata sandi Anda",
    silahkanIsiAlamatEmail: "Silahkan isi alamat email anda",
    loginKeEezeelink: "Login ke Ezeelink Payment Gateway",
    login: "Login",
    pilihBahasa: "Pilih Bahasa",
    bahasa: "Bahasa",
    inggris: "Inggris",
    china: "China",
    tabelRiwayatSettlementPartner: "Tabel Riwayat Settlement Partner",
    riwayatSettlement: "Riwayat Settlement",
    jumlah: "Jumlah",
    vapartner: "VA Partner",
    emoney: "E-Money",
    detailSettlement: "Detail Settlement",
    noVa: "No VA",
    tipePeriode: "Tipe Periode",
    placeholderTipePeriode: "Pilih Tipe Periode",
    periodeBuat: "Periode Buat",
    periodeProses: "Periode Proses",
    waktuPembayaran: "Waktu Pembayaran"
}

export var eng = {
    flag: EN,
    flagName: "EN",
    detailAkun: "Account Detail",
    topUpSaldo: "Balance Top Up",
    riwayatTopUp: "Top Up History",
    saldoTersedia: "Available Balance : ",
    laporan: "Report",
    danaMasuk: "Cash In",
    namaAgen: "Agent Name",
    placeholderNamaAgen: "Choose Agent Name",
    status: "Status",
    placeholderStatus: "Choose Status",
    berhasil: "Success",
    dalamProses: "In Process",
    gagal: "Failed",
    menungguPembayaran: "Waiting for Payment",
    kadaluwarsa: "Expired",
    riwayatDisburse: "Disbursement Report",
    filter: "Filter",
    idTransaksi: "Transaction ID",
    placeholderIdTrans: "Enter Transaction ID",
    periode: "Period",
    pilihPeriode: "Choose Period",
    hariIni: "Today",
    kemarin: "Yesterday",
    tujuhHariTerakhir: "Last 7 Days",
    bulanIni: "This Month",
    bulanKemarin: "Last Month",
    pilihRangeTanggal: "Choose Date Range",
    jenisTransaksi: "Transaction Type",
    placeholderJenisTransaksi: "Choose Transaction Type",
    paymentLink: "Payment Link",
    virtualAccount: "Virtual Account",
    namaBank: "Bank Name",
    placeholderNamaBank: "Choose Bank Name",
    partnerTransId: "Partner Trans ID",
    placeholderPartnerTransId: "Enter Partner Trans ID",
    terapkan: "Apply",
    aturUlang: "Reset",
    no: "No",
    waktu: "Transaction Time",
    nominalTransaksi: "Transaction Amount",
    biaya: "Fee",
    nominalDisburse: "Disbursement Amount",
    totalDisburse: "Disbursement Total",
    tujuanDisburse: "Disbursement Destination",
    cabang: "Branch",
    nomorRekTujuan: "Beneficiary Account Number",
    namaPemilikRek: "Beneficiary Account Name",
    catatan: "Notes",
    totalSettlement: "Settlement Amount",
    tidakAdaData: "There are no record to display",
    riwayat: "History",
    collectionEwallet: "E-Wallet Collection",
    channel: "Channel",
    channelEwallet: "Choose eWallet Channel",
    directDebit: "Direct Debit",
    namaUser: "User name",
    placeholderNamaUser: "Choose User name",
    noHandphone: "Phone Number",
    infoSaldoDanMutasi: "Balance & Mutation Report",
    pilihAkun: "Choose Account",
    saldoRekSubAkun: "Sub Account Balance",
    klikUntukLihatSaldo: "Click to View Balance",
    noRekSubAkun: "Sub Account - Account Number",
    atasNama: "p.p.",
    mutasiRekSubAkun: "Sub Account Mutation Report",
    idRefBank: "Bank Reference ID",
    placeholderIdRefBank: "Enter Reference ID",
    idRefTrans: "Transaction Reference ID",
    placeholderIdRefTrans: "Enter Transaction Reference ID",
    rekTujuan: "Destination Bank",
    nominal: "Amount",
    deskripsi: "Description",
    keterangan: "Information",
    disbursement: "Disbursement",
    disbursementManual: "Manual Disbursement",
    disbursementBulk: "Bulk Disbursement",
    descManualDisburse: "Make sure the Disbursement destination data is correct, Ezeelink is not responsible for data errors made.",
    pilihBankTujuan: "Choose Destination Bank",
    pilihBank: "Choose Bank",
    descBankTujuan: "Transfers after 12 pm to banks other BCA have the potential to be received in the next day",
    placeholderCabangBank: "Input Branch",
    noRekTujuan: "Beneficiary Account Number",
    placeholderNoRekTujuan: "Input Beneficiary Account Number",
    placeholderNamaPemilikRek: "Input Beneficiary Account Name",
    simpanKeDaftarRek: "Save to Account List",
    lihatDaftarRek: "View Account List",
    daftarRekening: "Account List",
    bankTujuan: "Destination Bank",
    noRek: "Account Number",
    cariDaftarBank: "Search Bank :",
    placeholderNamaKodeBank: "Input Bank Name/Bank Code",
    batal: "Cancel",
    descNominalDisburse: "Amount of disbursement shouldn't contain decimal",
    descPilihTujuanBank: "Please select the destination bank first",
    descMinimalDisburse: "Minimum of Disbursement is",
    emailPenerima: "Beneficiarry Email",
    placeholderEmailPenerima: "Input Beneficiary Email Address",
    placeholderCatatan: "Input Note If Needed (Max. 25 character)",
    tambahTujuanDisburse: "Add Disbursement",
    simpan: "Save",
    aksi: "Action",
    belumAdaDataDisburse: "There is no data yet",
    ringkasan: "Summary",
    totalFeeDisbursePlusTax: "Total of Fee Disbursement + Total Tax",
    totalDisbursePlusFee: "Total of Disbursement + Total Fees",
    sisaSaldoTersedia: "Remaining Balance",
    descTerhitung: "(Calculated after disbursement completed)",
    lakukanDisburse: "Submit Disbursement",
    daftarBank: "Bank List",
    placeholderDaftarBank: "Input Bank Name / Bank Code",
    kodeBank: "Bank Code",
    descSubDisburseBulk: "Please view the template filling guide to avoid mistakes:",
    lihatPanduan: "See Guides",
    unduhTemplate: "Download Template",
    letakkanFile: "Select or drop your Excel file here. <br/> Make sure the Excel file is correct, you can't cancel files that have been uploaded and disbursed.",
    unggahFile: "Upload File",
    kontenTidakSesuai: "The content in the table does not match the Ezeelink Bulk <br/> Disbursement template. Please download and use the template provided <br/> to make it easier to check disbursement data",
    gantiFile: "Change File",
    formatFileExcel: "The file must be in Excel format",
    seluruhDataBankTidakTersedia: "All Destination Bank is not available right now",
    riwayatTransaksi: "Transaction Report",
    riwayatSaldo: "Balance Report",
    tipeSaldo: "Balance Type",
    placeholderTipeSaldo: "Choose Balance Type",
    export: "Export",
    totalHalaman: "Page Total",
    saldoSebelum: "Balance Before",
    saldoSesudah: "Balance After",
    nominalTopUpSaldo: "Top Up Amount",
    rp: "IDR",
    topUp: "TOP UP",
    selesaikanProsesTopUp: "Please Complete Your Top Up",
    selesaikanPembayaran: "Complete Your Payment In",
    batasAkhir: "Expired date ",
    metodePembayaran: "Payment Method",
    transferBank: "Bank Transfer",
    nominalTransfer: "Amount of Transfer",
    salin: "Copy",
    lakukanTransfer: "Make a transfer according to the nominal listed up to the last 3 digits.",
    sayaSudahTransfer: "I ALREADY TRANSFER",
    tanggal: "Date",
    konfigurasi: "Configuration",
    aktif: "Active",
    tidakAktif: "Inactive",
    idPartner: "Partner ID",
    namaPerusahaan: "Company Name",
    emailPerusahaan: "Company Email",
    noTelp: "Phone Number",
    alamat: "Address",
    noNpwp: "NPWP Number",
    namaNpwp: "NPWP Name",
    sumberAgen: "Agent Source",
    namaDirektur: "Director Name",
    noHpDirektur: "Phone Number",
    daftarAgen: "Agent List",
    tambahAgen: "Add New Agent",
    cariNamaAgen: "Search Agent",
    placeholderCariNamaAgen: "Enter Agen Name",
    idAgen: "Agent ID",
    email: "Email",
    default: "Default",
    kodeUnik: "Unique Code",
    detailAgen: "Agent Details",
    emailAgen: "Email",
    noHpAgen: "Agent Phone Number",
    silahkanHubungiAdmin: "Please contact Admin to add Sub Account to the Agent",
    rekSubAkun: "Sub Account Details",
    tambahAgenBaru: "Add New Agent",
    emailSudahTerdaftar: "Email has been registered",
    noHpSudahTerdaftar: "Phone number has been registered",
    biayaSettlement: "Settlement Fee",
    tambahkan: "Add Agent",
    agenBerhasilDitambah: "Agent added succesfully",
    agenSudahAktif: "The agent is active and agent transactions will be recorded on your dashboard",
    idAgenDanKodeUnik: "Agent ID & Unique Code",
    oke: "Okay",
    membatalkanPerubahanDataPartner: "Are you sure to cancel the change?",
    dataKembaliKondisiSemula: "The change will be not saved",
    menyimpanDataPerubahan: "Are you sure to save the change?",
    perubahanDataBaru: "The change will be saved as a new data on the agent",
    menonaktifkanAgen: "Are you sure to deactivate the agent?",
    transaksiAgenTidakTersimpan: "Their transactions will not saved in dashboard",
    aktifkanAgen: "Are you sure to activate the agent?",
    transaksiAgenTersimpan: "Their transactions will be saved in dashboard",
    daftarUserDirectDebit: "Direct Debit User List",
    namaPartner: "Partner Name",
    idUser: "User ID",
    detailIdUser: "User ID Details",
    descIdUser: "User ID is a unique code obtained from the Bank in the form of a combination of numbers and alphanumeric and cannot be changed by the admin",
    idUserTersalin: "User ID Copied",
    buatPaymentLink: "Create Payment Link",
    paymentId: "Payment ID",
    placeholderPaymentId: "Enter Payment ID",
    idRef: "Reference ID",
    placeholderIdRef: "Enter Reference ID",
    tanggalPembuatan: "Created Date",
    settlement: "Settlement",
    ditutup: "Closed",
    detail: "Details",
    minNominalTagihan: "Minimum billing amount is IDR 10.000",
    aturWaktu: "Set Time",
    masaKadaluarsa: "The expired time cannot less than 5 minutes",
    batasPemakaian: "Usage Limit",
    catatanBatasPemakaian: "Note: Usage limit is how many link can be accessed",
    semuaMetodePembayaran: "All Payment Method",
    aturBeberapa: "Set Up Multiple Payment Methods",
    placeholderDeskripsi: "Input Description",
    customDesignPaymentLink: "Customize Your Payment Page Design",
    previewTampilan: "Page Preview",
    logoAnda: "Your Logo",
    namaPerusahaanAnda: "Your Company Name",
    totalPembayaran: "Amount Total",
    nama: "Name",
    placeholderNama: "Enter your name",
    placeholderEmail: "Enter your email",
    descPreviewTampilan: "We will use this data to send proof of payment transactions via your email",
    lanjutkan: "Continue",
    aturTampilan: "Manage View",
    logoPerusahaan: "Company Logo",
    uploadFile: "Upload File",
    ukuranFileCustom: "Dimension 2:1, max size 500kb",
    simpanPerubahan: "Save Changes?",
    seluruhPerubahanTersimpan: "All changes will be saved and the payment page will be updated",
    seluruhPerubahanTerhapus: "All changes will be erased and the display will be returned as before",
    batalkanPerubahan: "Batalkan Perubahan?",
    batalkan: "Cancel",
    kembali: "Back to Edit",
    biayaAdmin: "Admin Fee",
    transaksi: "Transaction",
    transaksiDirectDebitUser: "Direct Debit User Transaction",
    channelDirectDebit: "Direct Debit Channel",
    periodeTransaksi: "Transaction Period",
    statusTransaksi: "Transaction Status",
    masukkanKataSandiSub: "Enter your login password",
    kataSandi: "Password",
    placeholderKataSandi: "Enter your password",
    lihatSaldo: "View Balance",
    panduanPengisianDisburseBulk: "Bulk Disbursement Guide",
    descPanduanDisburseBulk: "Make sure the Disbursement destination data is correct, Ezeelink is not responsible for data errors made, and will still be charged according to the Disbursement Fee.",
    panduan1: "Uploaded files must be in excel format, and cannot use other formats",
    panduan2: "Uploaded files must use the template file provided, you cannot create your own format",
    panduan3: "Please do not change or add sheet names, table names, table order and table data types. Renaming files is allowed as needed",
    panduan4: "Required - Destination Bank is filled in according to the list of disbursement destination banks and must include the bank code. For bank codes with a prefix of 0, it must be written in single quote to minimize errors in excel data (Example: '014-BCA) The list of banks can be seen in the following file: ",
    panduan5: "Required to be filled specifically for the destination branch of a bank other than BCA. If the selected bank is BCA then it can be left blank",
    panduan6: "Required - Destination Account Number is filled in according to the destination bank account format. Use a number format and please pay attention to the account digits. For account numbers with 0 in the front, it must be written in single quote to minimize errors in excel data (Example: '098765421)",
    panduan7: "Required - Name of Account Holder must be filled in correctly and correctly",
    panduan8: "Required - Nominal Disbursement is filled in IDR format. Nominal disbursements cannot contain decimals",
    panduan9: "Beneficiary email is optional and can be filled in to send successful Disburse notifications. If the email is not filled, it can be left blank",
    panduan10: "Notes can be filled if needed and are optional and a maximum of 25 characters (including spaces).",
    panduan11: "Branch, Account Name, Email and Notes Column must be written in alphabeth",
    daftarBankTujuan: "List of Destination Banks",
    mengerti: "Agree",
    kesalahanDataPerluDiperbaiki: "Data that need to fix",
    dataPadaBarisKe: "Line ",
    barisKe: "",
    konfirmasiDisburse: "Disbursement Confirmation",
    descKonfirmasiDisburse: "Please make sure all disbursement data is correct. Errors in the data can cause disbursement failures and will still be charged according to the specified Disbursement Fee.",
    saldoTidakCukup: "Insuficient Balance, please Top Up your balance before continuingDisbursement",
    sayaBertanggungJawab: "I am responsible for the entire correctness or falsity of the data above",
    silahkanCobaUploadUlang: "Please try again in a few minutes, or contact Admin for further information",
    jumlahSheetPadaFileExcel: "there is more than 1 sheet in the file. Please Please review your file to ensure it matches the template.",
    dataPadaFileMasihKosong: "The file is empty.",
    kolomBankTujuanWajibDiisi: `Bank Destination column : Required to fill`,
    kolomBankTujuanSalah : "Bank Destination column : The destination bank is invalid or not available at the moment",
    kolomNoRekWajibDiisi: "Account Number column : Required to fill",
    kolomNoRekTipeDataSalah: "Account Number column : Invalid data type",
    kolomNoRekDigitRekTidakSesuai: "Account Number column : The digit of the account number doesn't match with the destination bank",
    kolomCabangTidakTersedia: "Branch column : The branch is invalid",
    kolomCabangWajibDiisi: "Branch column : Required to fill",
    kolomNominalDisburseWajibDiisi: "Disbursement Amount column : Required to fill",
    kolomNominalDisburseTipeDataSalah: "Disbursement Amount column : Invalid data type",
    kolomNominalDisburseMinNominal: "Disbursement Amount column : Minimum of Disbursement",
    kolomNominalDisburseMaksNominal: "Disbursement Amount column : Maximum of Disbursement",
    kolomNominalDisburseTidakBolehDesimal: "Amount of disbursement shouldn't contain decimal",
    saldoAndaTidakCukup: "Insuficient Balance",
    pilihFile: "Choose File",
    descSectionOneSub: "You will need to know your ",
    partnerId: "Partner ID",
    dan: "and ",
    descSectionTwoSub: "to communicate with Ezeelink. Please use the Development server while you are still in development.",
    thisKeyInKonfigurasi: "This key is auto generated by system and should not be changed. If you really need to change your key for some reason, please contact our contact support",
    hubungiKami: "contact support",
    ezeelinkMemerlukanUrl: "Ezeelink requires the URL endpoints for for the following scenarios:",
    paymentNotifUrl: "Payment Notification URL",
    addressUrl: "Address where we will send the notification via HTTP Post request. E.g http://yourwebsite.com/notification/handing",
    update: "Update",
    mohonTunggu: "Please wait",
    subAccount: "Sub Account",
    subAccountBank: "Bank Sub Account",
    transfer: "Transfer",
    placeholderNominalTransfer: "Input Amount of Transfer",
    periksa: "Check",
    rekeningTerkonfirmasi: "Account confirmed",
    silahkanPilihBankDahulu: "Please select bank",
    biayaTransfer: "Transfer Fee",
    transferSekarang: "Transfer Now",
    konfirmasiTransfer: "Confirm Transfer",
    dariRek: "From ",
    bank: "Bank",
    total: "Total",
    konfirmasiOtp: "Confirm OTP",
    kodeVerifikasi: "Verification code has been sent via message to",
    tidakMenerimaOtp: "Doesn't receive OTP?",
    kirimUlang: "Resend",
    mohonTungguDalam: "Please wait in",
    untukKirimUlang: "to resend",
    maksimumPermintaanOtp: "Maximum OTP Request",
    konfirmasi: "Confirm",
    andaMencapaiMaksPermintaanOtp: "You have reach the maximum OTP request for today!",
    batasMaksimumOtp: "The maximum limit is 3 OTP requests per day. Try again in the next 1x24 hours to make an OTP request.",
    cekMutasi: "Check mutations periodically to find out transfer status",
    unduhBuktiTf: "Download Transaction Receipt",
    lihatMutasi: "See Mutations",
    show: "Show",
    entries: "entries",
    detailPaymentLink: "Payment Link Details",
    dibuatPada: "Created at",
    tanggalKadaluarsa: "Expired date",
    batasPembayaran: "Payment Deadline",
    tutupPaymentLink: "Close Payment Link",
    placeholderNominalTagihan: "Input Amount of Bill",
    biayaAdminPaymentLink: "Fee : IDR 0 (Deducted to Partner)",
    catatanIdRef: "Notes : Reference ID can be words or numeric digits",
    silahkanHubCs: "Please contact our customer service to set payment methods",
    selamatPaymentLinkBerhasilDibuat: "Your payment link has been successfully created",
    linkTersalin: "Copied",
    salinLink: "Copy Link",
    silahkanSalinLink: "Please copy the link above to receive payments",
    tutup: "Close",
    yakinInginKeluar: "Are you sure to leave this page?",
    seluruhPerubahan: "All changes will be deleted",
    keluar: "Log Out",
    tidak: "No",
    aturMetodePembayaran: "Set Payment Method",
    metodePembayaranHarusDipilih :"Please choose payment method!",
    ya: "Yes",
    edit: "Edit",
    placeholderEmailAgen: "Enter Agent Email",
    placeholderNoHpAgen: "Enter Agent Phone Number",
    placeholderNoRek: "Input Account Number",
    placeholderSettleFee: "Input Amount of Settlement Fee",
    dataTidakValid: "Invalid Data",
    maksimalDisburse: "Max Amount of Disbursement",
    formatEmail: `Email must contain "@". Example : name@mail.com`,
    kolomNomorRekDigitNomorRek: "Account Number column : The digit of the account number doesn't match with the destination bank",
    salinId: "Copy",
    cabangKhususNonBca: "Branch (Specifically non-BCA)",
    disburseSedangDiproses: "Disbursement is on Process.",
    lihatRiwayatDisburse: "Go to Disbursement History",
    logout: "Log Out",
    harapPerbaikiData: "Please fix your data before uploading file",
    yakinPindahHalaman: "Are you sure to leave this page?",
    ditemukanDuplikasiData: "Data Duplication Found, Still Continue?",
    dataInginDitambahkanTelahTersedia: "The data is already available in the table.",
    perbaiki: "Fix",
    kolomNamaPemilikRekWajibDiisi: "The account name must be filled in",
    kolomNomorRekTipeDataSalah: "Account Number column : Invalid data type",
    kolomEmailPenerimaTipeDataSalah: "Beneficiary Email column : Invalid data type",
    kolomCatatanMaksKarakter: "Notes column : Max. 25 character",
    bankTujuanStar: "Destination Bank*",
    noRekTujuanStar: "Beneficiary Account Number*",
    namaPemilikRekStar: "Beneficiary Account Name*",
    nominalDisburseStar: "Disbursement Amount*",
    cabangStar: "Branch*",
    emailPenerimaStarAlpabet: "Beneficiary Email",
    catatanStarAlpabet: "Notes",
    placeholderNamaPerusahaan: "Enter your company name",
    lihatSemua: "See All",
    letakkanFileWithCsv: "Select or drop your Excel (*.csv) file here. <br/> Make sure the Excel file is correct, you can't cancel files that have been uploaded and disbursed.",
    kataSandiSalah: "Wrong password",
    sistemSedangBermasalah: "There's a problem in the system",

    descSistemBermasalah: "Currently our system is having a problem to show your balance. Please try again later",
    saldoRekSubAccount: "Sub Account-Account Balance",
    nominalSaldoSaatIni: "Current Balance",
    seluruhDataDiinputAkanTerhapus: "All data will be deleted if you leave this page, still want to continue?",
    kembaliKeLoginPage: "Back to Login Page",
    lupaKataSandi: "Forgot Password",
    descKataSandi: "Enter the email that registered and we will send you an email with a link to reset your password",
    placeholderMasukkanEmail: "Input Email",
    kirimLink: "Send Link",
    linkBehasilDikirim: "Link Sent",
    periksaEmailDanIkutiInstruksi: "Please check your email and follow the instructions to reset your password",
    silahkanIsiAlamatEmail: "Please fill in your email address",
    loginKeEezeelink: "Login to Ezeelink Payment Gateway",
    login: "Login",
    pilihBahasa: "Choose Language",
    bahasa: "Indonesia",
    inggris: "English",
    china: "China",
    tabelRiwayatSettlementPartner: "Partner Settlement Report",
    riwayatSettlement: "Settlement Report",
    jumlah: "Amount",
    vapartner: "VA Partner",
    emoney: "E-Money",
    detailSettlement: "Settlement Details",
    noVa: "VA Number",
    tipePeriode: "Date Periode Type",
    placeholderTipePeriode: "Choose Period Type",
    periodeBuat: "Create Period",
    periodeProses: "Processing Period",
    waktuPembayaran: "Payment Date"
}

export var chn = {
    flag: CN,
    flagName: "CN",
    detailAkun: "账户详情",
    topUpSaldo: "余额充值",
    riwayatTopUp: "充值历史",
    saldoTersedia: "可用余额：",
    laporan: "报告",
    danaMasuk: "兑现",
    namaAgen: "代理名",
    placeholderNamaAgen: "代理名字",
    status: "状态",
    placeholderStatus: "选择状态",
    berhasil: "成功",
    dalamProses: "正在办理",
    gagal: "无效",
    menungguPembayaran: "等待付款",
    kadaluwarsa: "过期",
    riwayatDisburse: "支付报告",
    filter: "筛选",
    idTransaksi: "交易ID",
    placeholderIdTrans: "交易ID",
    periode: "周期",
    pilihPeriode: "选择日期",
    hariIni: "今天",
    kemarin: "昨天",
    tujuhHariTerakhir: "前 7 天",
    bulanIni: "这个月",
    bulanKemarin: "上个月",
    pilihRangeTanggal: "选择日期范围",
    jenisTransaksi: "交易类型",
    placeholderJenisTransaksi: "选择交易类别",
    paymentLink: "付款链接",
    virtualAccount: "虚拟账户",
    namaBank: "银行名",
    placeholderNamaBank: "选择银行名",
    partnerTransId: "合作伙伴交易ID",
    placeholderPartnerTransId: "输入合作伙伴交易ID",
    terapkan: "申请",
    aturUlang: "重置",
    no: "编号",
    waktu: "交易时间",
    nominalTransaksi: "交易额度",
    biaya: "费用",
    nominalDisburse: "支付额度",
    totalDisburse: "支出总额",
    tujuanDisburse: "付款目的地",
    cabang: "分支",
    nomorRekTujuan: "收款人账号",
    namaPemilikRek: "收款人账户名称",
    catatan: "注释",
    totalSettlement: "结算额度",
    tidakAdaData: "无数据可显示",
    riwayat: "历史",
    collectionEwallet: "电子钱包集合",
    channel: "渠道",
    channelEwallet: "电子钱包渠道",
    directDebit: "直接借记",
    namaUser: "用户名",
    placeholderNamaUser: "选择用户名",
    noHandphone: "电话号码",
    infoSaldoDanMutasi: "余额信息和转账记录",
    pilihAkun: "选择账户",
    saldoRekSubAkun: "子账户余额",
    klikUntukLihatSaldo: "点击查看余额",
    noRekSubAkun: "子账户 - 账号",
    atasNama: "p.p.",
    mutasiRekSubAkun: "子账户转账记录",
    idRefBank: "银行参考ID",
    placeholderIdRefBank: "输入参考ID",
    idRefTrans: "交易参考ID",
    placeholderIdRefTrans: "输入交易参考ID",
    rekTujuan: "目标银行",
    nominal: "额度",
    deskripsi: "描述",
    keterangan: "明细",
    disbursement: "支出",
    disbursementManual: "手动付款",
    disbursementBulk: "批量支付",
    descManualDisburse: "请确保付款目的地数据正确，Ezeelink 对数据错误不承担任何责任。",
    pilihBankTujuan: "选择目标银行",
    pilihBank: "选择银行",
    descBankTujuan: "中午 12 点后转账至除 BCA 银行意外可能会在第二天才收到转账",
    placeholderCabangBank: "输入分支",
    noRekTujuan: "收款人账号",
    placeholderNoRekTujuan: "输入收款人账号",
    placeholderNamaPemilikRek: "输入收款人账户名称",
    simpanKeDaftarRek: "保存到账号列表",
    lihatDaftarRek: "查看账户列表",
    daftarRekening: "账户列表",
    bankTujuan: "目标银行",
    noRek: "账号",
    cariDaftarBank: "搜索银行 :",
    placeholderNamaKodeBank: "输入银行名称/银行代码",
    batal: "取消",
    descNominalDisburse: "支付金额不能包含小数",
    descPilihTujuanBank: "请先选择目标银行",
    descMinimalDisburse: "最低付款额为",
    emailPenerima: "收款人电子邮件",
    placeholderEmailPenerima: "输入收款人电子邮件地址",
    placeholderCatatan: "如果需要，请输入注释（最多 25 个字符）",
    tambahTujuanDisburse: "添加支出",
    simpan: "保存",
    aksi: "动态",
    belumAdaDataDisburse: "还没有数据",
    ringkasan: "概括",
    totalFeeDisbursePlusTax: "费用支付总额 + 税金总额",
    totalDisbursePlusFee: "支出总额 + 费用总额",
    sisaSaldoTersedia: "剩余余额",
    descTerhitung: "(支付完成后计算)",
    lakukanDisburse: "提交付款",
    daftarBank: "银行名单",
    placeholderDaftarBank: "输入银行名称/银行代码",
    kodeBank: "银行代码",
    descSubDisburseBulk: "请查看模板填写指南以避免错误：",
    lihatPanduan: "查看指南",
    unduhTemplate: "下载模板",
    letakkanFile: "在此处选择或放置您的 Excel 文件。<br/> 确保Excel文件正确，已上传和支付的文件无法取消。",
    unggahFile: "上传文件",
    kontenTidakSesuai: "表中的内容与 Ezeelink 批量付款模板不匹配。 请下载并使用提供的模板，以便查看付款数据",
    gantiFile: "更改文件",
    formatFileExcel: "文件必须是 Excel 格式",
    seluruhDataBankTidakTersedia: "目前无法使用所有目标银行",
    riwayatTransaksi: "历史交易",
    riwayatSaldo: "余额明细",
    tipeSaldo: "余额类型",
    placeholderTipeSaldo: "选择余额类型",
    export: "出口",
    totalHalaman: "总页数",
    saldoSebelum: "前期余额",
    saldoSesudah: "后期余额",
    nominalTopUpSaldo: "充值金额",
    rp: "印尼盾",
    topUp: "充值",
    selesaikanProsesTopUp: "请完成充值",
    selesaikanPembayaran: "在内完成您的付款",
    batasAkhir: "过期日期 ",
    metodePembayaran: "付款方式",
    transferBank: "银行转账",
    nominalTransfer: "转账金额",
    salin: "复制",
    lakukanTransfer: "根据所列名义最多最后 3 位数字进行转账",
    sayaSudahTransfer: "已转账",
    tanggal: "日期",
    konfigurasi: "配置",
    aktif: "激活",
    tidakAktif: "未激活",
    idPartner: "合作伙伴ID",
    namaPerusahaan: "公司名称",
    emailPerusahaan: "公司电子邮件",
    noTelp: "电话号码",
    alamat: "地址",
    noNpwp: "纳税人识别号号码",
    namaNpwp: "纳税人识别号名字",
    sumberAgen: "代理来源",
    namaDirektur: "经理名字",
    noHpDirektur: "电话号码",
    daftarAgen: "代理列表",
    tambahAgen: "添加新代理",
    cariNamaAgen: "搜索代理",
    placeholderCariNamaAgen: "输入代理名",
    idAgen: "代理ID",
    email: "电子邮件",
    default: "默认",
    kodeUnik: "特殊代码",
    detailAgen: "代理明细",
    emailAgen: "电子邮件",
    noHpAgen: "代理电话号码",
    silahkanHubungiAdmin: "联系管理员添加子账号至代理",
    rekSubAkun: "子账户明细",
    tambahAgenBaru: "添加新代理",
    emailSudahTerdaftar: "电子邮件已注册",
    noHpSudahTerdaftar: "电话号码已注册",
    biayaSettlement: "结算费用",
    tambahkan: "添加代理",
    agenBerhasilDitambah: "代理添加成功",
    agenSudahAktif: "代理已激活，代理交易将记录在仪表板上",
    idAgenDanKodeUnik: "代理ID&特殊码",
    oke: "好的",
    membatalkanPerubahanDataPartner: "您确定要取消更改吗？",
    dataKembaliKondisiSemula: "更改将不会保存",
    menyimpanDataPerubahan: "确定保存更改？",
    perubahanDataBaru: "更改将保存为代理上的新数据",
    menonaktifkanAgen: "您确定停用代理吗？",
    transaksiAgenTidakTersimpan: "他们的交易不会保存在控制面表",
    aktifkanAgen: "您确定激活代理吗？",
    transaksiAgenTersimpan: "他们的交易将保存在控制面表",
    daftarUserDirectDebit: "直接借记用户列表",
    namaPartner: "合作伙伴名称",
    idUser: "用户身份",
    detailIdUser: "用户ID明细",
    descIdUser: "用户 ID 是从银行获得的特码，采用数字和字母数字组合的形式，管理员无法更改",
    idUserTersalin: "用户ID已复制",
    buatPaymentLink: "创建付款链接",
    paymentId: "付款ID",
    placeholderPaymentId: "输入付款ID",
    idRef: "参考ID",
    placeholderIdRef: "输入参考ID",
    tanggalPembuatan: "创造日期",
    settlement: "结算 ",
    ditutup: "关闭",
    detail: "细节",
    minNominalTagihan: "最低账单金额为 10,000 印尼盾",
    aturWaktu: "设置时间",
    masaKadaluarsa: "过期时间不能少于5分钟",
    batasPemakaian: "使用限制",
    catatanBatasPemakaian: "注意：使用限制是可以访问的链接数",
    semuaMetodePembayaran: "所有付款方式",
    aturBeberapa: "设置多种付款方式",
    placeholderDeskripsi: "输入说明",
    customDesignPaymentLink: "定制付款页面设计",
    previewTampilan: "预览页面",
    logoAnda: "你的标志",
    namaPerusahaanAnda: "您的公司名称",
    totalPembayaran: "总金额",
    nama: "姓名",
    placeholderNama: "输入你的名字",
    placeholderEmail: "输入你的电子邮件",
    descPreviewTampilan: "我们将使用这些数据通过电子邮件发送付款交易证明",
    lanjutkan: "继续",
    aturTampilan: "管理视图",
    logoPerusahaan: "公司标志",
    uploadFile: "上传文件",
    ukuranFileCustom: "尺寸 2:1，最大大小 500kb",
    simpanPerubahan: "保存更改？",
    seluruhPerubahanTersimpan: "所有更改已保存并已更新付款页面",
    seluruhPerubahanTerhapus: "所有更改将被删除，显示将返回到以前的状态",
    batalkanPerubahan: "取消更改？",
    batalkan: "取消",
    kembali: "返回编辑",
    biayaAdmin: "手续费",
    transaksi: "交易",
    transaksiDirectDebitUser: "直接借记交易用户",
    channelDirectDebit: "直接借记渠道",
    periodeTransaksi: "交易周期",
    statusTransaksi: "交易状态",
    masukkanKataSandiSub: "输入您的登录密码",
    kataSandi: "密码",
    placeholderKataSandi: "输入密码",
    lihatSaldo: "查看余额",
    panduanPengisianDisburseBulk: "批量支付指南",
    descPanduanDisburseBulk: "确保支付目的地数据正确，Ezeelink对数据错误不承担任何责任，我们仍将按照支付费用收取费用。",
    panduan1: "上传的文件必须是excel格式，不能使用其他格式",
    panduan2: "上传的文件必须使用提供的模板文件，不能创建自己的格式",
    panduan3: "请勿更改或添加工作表名称、表名称、表顺序和表数据类型。 允许根据需要重命名文件",
    panduan4: "必填项 - 目标银行根据付款目标银行列表填写，且必须包含银行代码。 对于前缀为 0 的银行代码，必须用单引号书写，以尽量减少 Excel 数据中的错误（例如：'014-BCA） 银行列表可以在以下文件中看到：",
    panduan5: "需要专门针对BCA以外的银行目的地分行填写。 如果选择的银行是BCA则可以留空",
    panduan6: "必填 - 目的地账号按照目标银行账户格式填写。 使用数字格式，请注意账号数字。 对于前面有0的账号，必须用单引号书写，以尽量减少Excel数据中的错误（例如：'098765421）",
    panduan7: " 必填——账户持有人姓名必须正确填写",
    panduan8: "必填项 - 名义支出以 IDR 格式填写。 名义支出不能包含小数",
    panduan9: "收款人电子邮件是可选的，可以填写以发送成功的付款通知。 如果邮箱未填写，可以留空",
    panduan10: "备注可根据需要填写，为选填项，最多25个字符（含空格）。",
    panduan11: "支行名称，账号名，邮箱和注释必须使用字母填写",
    daftarBankTujuan: "目标银行列表",
    mengerti: "同意",
    kesalahanDataPerluDiperbaiki: "需要更改的数据",
    dataPadaBarisKe: "在第（",
    barisKe: "）行的数据",
    konfirmasiDisburse: "付款确认",
    descKonfirmasiDisburse: "请确保所有付款数据正确。 数据错误可能导致付款失败，仍将按照指定的付款费用收取费用。",
    saldoTidakCukup: "余额不足，请先充值再继续支付",
    sayaBertanggungJawab: "我对上述数据的全部正确性或虚假性负责",
    silahkanCobaUploadUlang: "请在几分钟后重试，或联系管理员了解更多",
    jumlahSheetPadaFileExcel: "文件多于 1 页。 请检查您的文件以确保文件与模板互相匹配。",
    dataPadaFileMasihKosong: "文件为空",
    kolomBankTujuanWajibDiisi: "“银行目的地”栏：必填",
    kolomBankTujuanSalah : "“银行目的地”栏：目的地银行无效或目前不可用",
    kolomNoRekWajibDiisi: "「账号」栏：必填",
    kolomNoRekTipeDataSalah: "「账号」栏：信息无效",
    kolomNoRekDigitRekTidakSesuai: "「账号」栏：账号位数与目的地银行不符",
    kolomCabangTidakTersedia: "“银行分支”栏：此分支银行无效",
    kolomCabangWajibDiisi: "“银行分支”栏：必填",
    kolomNominalDisburseWajibDiisi: "“支付金额”栏：必填",
    kolomNominalDisburseTipeDataSalah: "“支付金额”栏：信息无效",
    kolomNominalDisburseMinNominal: "“支付金额”栏：最低支付金额为印尼币 ",
    kolomNominalDisburseMaksNominal: "“支付金额”栏：最高支付金额为印尼币 ",
    kolomNominalDisburseTidakBolehDesimal: "支付金额不能包含小数",
    saldoAndaTidakCukup: "余额不足",
    pilihFile: "选择文件",
    descSectionOneSub: "为了能使用Ezeelink交流，需要您的",
    partnerId: "合作伙伴ID",
    dan: "和",
    descSectionTwoSub: "请在开发过程中使用开发服务器。",
    thisKeyInKonfigurasi: "该密钥由系统自动生成，不应更改。 如果因某种原因需要更改密钥，",
    hubungiKami: "请联系我们的联系支持人员。",
    ezeelinkMemerlukanUrl: "Ezeelink 需要以下场景的 URL 端点：",
    paymentNotifUrl: "URL ......",
    addressUrl: "我们将通过 HTTP Post 请求发送通知的地址。 例如http://yourwebsite.com/notification/handing",
    update: "更新",
    mohonTunggu: "请耐心等待",
    subAccount: "子账号",
    subAccountBank: "银行子账号",
    transfer: "转账",
    placeholderNominalTransfer: "输入转账金额",
    periksa: "检查",
    rekeningTerkonfirmasi: "账号已确认",
    silahkanPilihBankDahulu: "请选择银行",
    biayaTransfer: "转账费",
    transferSekarang: "立即转账",
    konfirmasiTransfer: "确认转账",
    dariRek: "从",
    bank: "银行 ",
    total: "总额",
    konfirmasiOtp: "确认验证码",
    kodeVerifikasi: "验证码已通过短信发送至",
    tidakMenerimaOtp: "没有收到验证码",
    kirimUlang: "重新发送",
    mohonTungguDalam: "请在",
    untukKirimUlang: "等待重新发送",
    maksimumPermintaanOtp: "验证码请求上限",
    konfirmasi: "确认",
    andaMencapaiMaksPermintaanOtp: "您已达到今天验证码请求上限！",
    batasMaksimumOtp: "每天的最大限制为 3 个 验证码请求。 请在接下来的 1x24 小时内重试以发出验证码请求。",
    cekMutasi: "定期检查突变以了解转移状态",
    unduhBuktiTf: "下载交易收据",
    lihatMutasi: "参见金额变动",
    show: "展示",
    entries: "分录",
    detailPaymentLink: "付款明细",
    dibuatPada: "创建于",
    tanggalKadaluarsa: "有效至",
    batasPembayaran: "付款截止",
    tutupPaymentLink: "关闭付款链接",
    placeholderNominalTagihan: "输入账单金额",
    biayaAdminPaymentLink: "费用：印尼盾 0（扣除给合伙人）",
    catatanIdRef: "注意：参考ID可以使用字体或者数字",
    silahkanHubCs: "请联系客户为设置付款方法",
    selamatPaymentLinkBerhasilDibuat: "您的付款链接已经成功创建",
    linkTersalin: "已复制",
    salinLink: "关闭链接",
    silahkanSalinLink: "请复制以上链接以便收款",
    tutup: "关闭",
    yakinInginKeluar: "确定离开此页面吗？",
    seluruhPerubahan: "所有更改已被删除",
    keluar: "退出",
    tidak: "否",
    aturMetodePembayaran: "设置付款方式",
    metodePembayaranHarusDipilih :"请选择付款方式",
    ya: "是",
    edit: "编辑",
    placeholderEmailAgen: "输入代理邮箱",
    placeholderNoHpAgen: "输入代理手机号",
    placeholderNoRek: "输入账号",
    placeholderSettleFee: "输入结算费",
    dataTidakValid: "数据无效",
    maksimalDisburse: "最高支付金额",
    formatEmail: `电子邮件必须包含“@”。 示例：name@mail.com`,
    kolomNomorRekDigitNomorRek: "「账号」栏：账号位数与目的地银行不符",
    salinId: "复制",
    cabangKhususNonBca: "分支机构（特别是非 BCA）",
    disburseSedangDiproses: "正在处理付款.",
    lihatRiwayatDisburse: "查看支付历史记录",
    logout: "退出",
    harapPerbaikiData: "请在上传之前更改信息",
    yakinPindahHalaman: "确定要离开页面吗？",
    ditemukanDuplikasiData: "发现数据重复，仍然要继续吗？",
    dataInginDitambahkanTelahTersedia: "数据已经提供在表中",
    perbaiki: "更改",
    kolomNamaPemilikRekWajibDiisi: "必须填账户名称",
    kolomNomorRekTipeDataSalah: "「账号」栏：信息无效",
    kolomEmailPenerimaTipeDataSalah: "收款人电子邮件列：数据类型无效",
    kolomCatatanMaksKarakter: "“注释”栏：最大为25 个字符",
    bankTujuanStar: "目标银行*",
    noRekTujuanStar: "收款人账号*",
    namaPemilikRekStar: "账号名称（必须使用字母填写）*",
    nominalDisburseStar: "支付额度*",
    cabangStar: "支行名称（必须使用字母填写）*",
    emailPenerimaStarAlpabet: "受益人邮箱（必须使用字母填写）",
    catatanStarAlpabet: "注释（必须使用字母填写）",
    placeholderNamaPerusahaan: "请输入公司名称",
    lihatSemua: "查看全部",
    letakkanFileWithCsv: "在此处选择或放置您的 Excel (*.csv) 文件。<br/> 确保Excel文件正确，已上传和支付的文件无法取消。",
    kataSandiSalah: "密码错误",
    sistemSedangBermasalah: "系统异常",

    descSistemBermasalah: "目前系统出现问题，无法显示当前余额，请稍后再试",
    saldoRekSubAccount: "子账号-账号余额",
    nominalSaldoSaatIni: "当前余额",
    seluruhDataDiinputAkanTerhapus: "当你离开页面时，所有的数据将被删掉，仍要继续吗？",
    kembaliKeLoginPage: "返回登录页",
    lupaKataSandi: "忘记密码",
    descKataSandi: "请输入用于注册的电子邮件，我们将向您发送一封包含重置密码链接的邮件",
    placeholderMasukkanEmail: "输入电子邮件",
    kirimLink: "发送链接",
    linkBehasilDikirim: "链接已发送",
    periksaEmailDanIkutiInstruksi: "请检查您的电子邮件并按照说明重置密码",
    silahkanIsiAlamatEmail: "请输入您的电子邮件",
    loginKeEezeelink: "登录Ezeelink 支付网关",
    login: "登录",
    pilihBahasa: "选择语言",
    bahasa: "印尼语",
    inggris: "英语",
    china: "中文",
    tabelRiwayatSettlementPartner: "合作伙伴结算记录",
    riwayatSettlement: "结算记录",
    jumlah: "金额",
    vapartner: "虚拟账户",
    emoney: "电子货币",
    detailSettlement: "结算细",
    noVa: "虚拟账户",
    tipePeriode: "日期 周期 类型",
    placeholderTipePeriode: "选择期间类型",
    periodeBuat: "创建期间",
    periodeProses: "处理期限",
    waktuPembayaran: "付款日期"
}