
export const Routes = {
    // pages
    DashboardOverview: { path: "/" },
    // DashboardOverview: { path: "/dashboard" },
    RiwayatTransaksi: { path: "/riwayattransaksi"},
    DetailAkun : { path: "/detailakun"},
    Transactions: { path: "/laporan" },
    Settings: { path: "/settings" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    DaftarAgen : { path: "/daftaragen" },
    TambahAgen : { path: "/tambahagen" },
    DetailAgen : { path: "/detailagen/:agenId" },
    EditAgen : { path: "/editagen/:agenId" },
    DaftarPartner : { path: "/daftarpartner" },
    TambahPartner : { path: "/tambahpartner" },
    DetailPartner : { path: "/detailpartner/:partnerId" },
    EditPartner : { path: "/editpartner/:partnerId" },
    ListMenuAccess : { path: "/menuaccess/:userId" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Login: { path: "/login" },
    Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/404" },
    ServerError: { path: "/examples/500" },

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};