export const Routes = {
    // pages
    DashboardOverview: { path: "/" },
    // DashboardOverview: { path: "/dashboard" },
    RiwayatTransaksi: { path: "/Riwayat/transaksi"},
    SaldoPartner: { path: "/Riwayat/saldopartner"},
    DetailSettlement: { path: "/detailsettlement/:settlementId/:bankCode/:settlementType/:eWalletCode"},
    DetailAkun : { path: "/detailakun"},
    Transactions: { path: "/laporan" },
    // Settings: { path: "/settings" },
    // Upgrade: { path: "/upgrade" },
    // BootstrapTables: { path: "/tables/bootstrap-tables" },
    DaftarAgen : { path: "/daftaragen" },
    TambahAgen : { path: "/tambahagen" },
    DetailAgen : { path: "/detailagen/:agenId" },
    EditAgen : { path: "/editagen/:agenId" },
    DaftarPartner : { path: "/daftarpartner" },
    TambahPartner : { path: "/tambahpartner" },
    DetailPartner : { path: "/detailpartner/:partnerId" },
    ListUser : { path: "/managementuser" },
    UpdateUser : { path: "/updateuser/:muserId" },
    EditPartner : { path: "/editpartner/:partnerId" },
    ListMenuAccess : { path: "/menuaccess/:userId" },
    RiwayatTopUp : { path: "/riwayattopup" },
    // AlokasiSaldo : { path: "/alokasisaldo" },
    ReNotifyVA : { path: "/helpDesk/renotifyva" },
    ReNotifyEwallet : { path: "/helpDesk/renotify-ewallet" },
    ReNotifyQris : { path: "/helpDesk/renotify-qris" },
    RiwayatDisbursement : { path: "/Disbursement/report" },
    // DisbursementReport : { path: "/disbursement-report" },
    // Billing: { path: "/examples/billing" },
    InvoiceVA: { path: "/invoiceva" },
    InvoiceDisbursement: { path: "/invoicedisbursement" },
    Login: { path: "/login" },
    // Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/forgot-password" },
    ResetPassword: { path: "/profile/changepassword" },
    // Lock: { path: "/examples/lock" },
    NotFound: { path: "/404" },
    // ServerError: { path: "/examples/500" },
    AddUser: {path:"/adduser"},
    ListPayment: {path: "/listpayment"},
    DetailPayment: {path: "/detailpayment/:paymentId"},
    AddPayment: {path: "/addpayment"},
    CustomDesignPayment: {path: "/custom-design-payment"},
    ListRiwayatSubAccountAdmin: {path: "/riwayat-sub-account-admin"},
    ListRiwayatSubAccount: {path: "/Sub Account Bank/riwayat-sub-account"},
    InfoSaldoDanMutasi: {path: "/Sub Account Bank/info-saldo-dan-mutasi"},
    TransferSubAccount: {path: "/Sub Account Bank/transfer"},
    TransaksiTopup: {path: "/transaksi/transaksi-topup"},

    // revamp menu
    UserDirectDebit: { path: "/user-direct-debit"},
    InvoiceVASubMenu: { path: "/buat-invoice/settlement" },
    InvoiceDisbursementSubMenu: { path: "/buat-invoice/disbursement" },
    RiwayatInvoice: { path: "/buat-invoice/invoice" },
    SaldoPartnerMenu: { path: "/riwayat-saldo-partner"},
    DisbursementPage : { path: "/disbursement" },
    SubAccountTransfer: {path: "/transfer-sub-account"},
    Settlement: { path: "/settlement/riwayat-settlement"},
    RiwayatBalance: { path: "/riwayat-balance" },
    GetBalance: { path: "/transaksi-bank"},
    QrisSettlement: {path: "/settlement/settlement-qris"},

    // admin
    VaDanPaymentLinkAdmin: {path: "/transaksi/va-dan-paylink"},
    RiwayatDirectDebitAdmin: {path: "/transaksi/direct-debit"},
    DisbursementAdmin: {path: "/transaksi/disbursement"},
    SubAccountAdmin: {path: "/transaksi/sub-account"},
    DisbursementTimeout: {path: "/transaksi/disbursement-timeout"},
    SettlementManual: {path: "/settlement/settlement-manual"},
    eWalletAdmin: {path: "/transaksi/ewallet"},
    RiwayatVAUSDAdmin: {path: "/transaksi/vausd"},
    QrisTransaksiAdmin: {path: "/transaksi/transaksi-qris"},
    TransaksiQrisApiAdmin: {path: "/transaksi/transaksi-qris-api"},
    ExcludeSettlementManual: {path: "/settlement/exclude-settlement"},
    ProsesSettlementManual: {path: "/settlement/proses-settlement-manual"},
    SettlementVAUSDAdmin: {path: "/settlement/va-usd"},
    VAUSD: {path: "/VA USD/create-va-usd"},
    RiwayatFileSFTP: {path: "/VA USD/riwayat-file-sftp"},
    UnsettledTransaction: {path: "/settlement/unsettled-transaction"},
    DaftarMerchantQris: {path: "/daftar-merchant-qris"},
    PilihJenisUsahaQris: {path: "/pilih-jenis-usaha"},
    FormInfoPemilikPerseorangan: {path: "/form-info-pemilik-perorangan"},
    FormInfoPemilikPerseoranganFirstStep: {path: "/form-info-pemilik-perorangan/:profileId"},
    FormInfoUsahaPerseorangan: {path: "/form-info-usaha-perorangan"},
    FormInfoUsahaPerseoranganSecondStep: {path: "/form-info-usaha-perorangan/:profileId"},
    FormInfoPemilikBadanUsaha: {path: "/form-info-pemilik-badan-usaha"},
    FormInfoPemilikBadanUsahaFirstStep: {path: "/form-info-pemilik-badan-usaha/:profileId"},
    FormInfoUsahaBadanUsaha: {path: "/form-info-usaha-badan-usaha"},
    FormInfoUsahaBadanUsahaSecondStep: {path: "/form-info-usaha-badan-usaha/:profileId"},
    FormDokumenUsahaBadanUsaha: {path: "/form-dokumen-usaha-badan-usaha"},
    FormDokumenUsahaBadanUsahaThirdStep: {path: "/form-dokumen-usaha-badan-usaha/:profileId"},
    FormTidakBerbadanHukum: {path: "/form-tidak-berbadan-hukum"},
    FormTidakBerbadanHukumFirstStep: {path: "/form-tidak-berbadan-hukum/:idProfile"},
    PengaturanMerchant: {path: "/pengaturan-merchant"},
    PengaturanMerchantEdit: {path: "/pengaturan-merchant/:idProfile/:level/:type"},
    FormDaftarSettlementEditData: {path: "/formulir-daftar-settlement/:settleGroup/:merchantNou/:userNou/:id"},
    DetailMerchantGrup: {path: "/detail-merchant-grup/:profileId"},
    FormTambahSettlement: {path: "/formulir-tambah-settlement"},
    FormTambahSettlementEdit: {path: "/formulir-tambah-settlement/:settleGroup/:merchantNou/:userNou"},
    DetailSettlementGrupQris: {path: "/detail-settlement/:profileId/:settleGroupId"},
    FormInfoPemilikBrand: {path: "/formulir-info-pemilik-brand"},
    FormInfoPemilikBrandFirstStep: {path: "/formulir-info-pemilik-brand/:profileId"},
    FormInfoUsahaBrandSecondStep: {path: "/formulir-info-usaha-brand/:profileId"},
    FormDokumenUsahaBrandThirdStep: {path: "/form-dokumen-usaha-brand-badan-usaha/:profileId"},
    FormInfoRekeningBrand: {path: "/form-info-rekening-brand"},
    FormInfoRekeningBrandEditStep: {path: `/form-info-rekening-brand/:settleGroup/:merchantNou/:userNou/:id`},
    DetailMerchantBrand: {path: "/detail-merchant-brand/:profileId"},
    FormInfoPemilikOutlet: {path: "/formulir-info-pemilik-outlet"},
    FormInfoPemilikOutletFirstStep: {path: "/formulir-info-pemilik-outlet/:profileId"},
    FormInfoUsahaOutletSecondStep: {path: "/formulir-info-usaha-outlet/:profileId"},
    FormDokumenUsahaOutletThirdStep: {path: "/form-dokumen-usaha-outlet/:profileId"},
    FormInfoRekeningOutletFourthStep: {path: "/form-info-rekening-outlet/:settleGroup/:merchantNou/:userNou/:id"},
    DetailMerchantOutlet: {path: "/detail-merchant-outlet/:profileId"},

    // partner
    VaDanPaymentLink: {path: "/riwayat-transaksi/va-dan-paylink"},
    RiwayatDirectDebit: {path: "/riwayat-transaksi/direct-debit"},
    Disbursement: {path: "/riwayat-transaksi/disbursement"},
    SubAccount: {path: "/riwayat-transaksi/sub-account"},
    eWallet: {path: "/riwayat-transaksi/ewallet"},
    RiwayatVAUSDPartner: {path: "/riwayat-transaksi/va-usd"},
    SettlementVAUSDPartner: {path: "/settlement/va-usd"},
    TransaksiQrisApi: {path: "/riwayat-transaksi/transaksi-qris-api"},
    QrisTransaksi: {path: "/riwayat-transaksi/transaksi-qris"},

    // docs
    // DocsOverview: { path: "/documentation/overview" },
    // DocsDownload: { path: "/documentation/download" },
    // DocsQuickStart: { path: "/documentation/quick-start" },
    // DocsLicense: { path: "/documentation/license" },
    // DocsFolderStructure: { path: "/documentation/folder-structure" },
    // DocsBuild: { path: "/documentation/build-tools" },
    // DocsChangelog: { path: "/documentation/changelog" },

    // components
    // Accordions: { path: "/components/accordions" },
    // Alerts: { path: "/components/alerts" },
    // Badges: { path: "/components/badges" },
    // Widgets: { path: "/widgets" },
    // Breadcrumbs: { path: "/components/breadcrumbs" },
    // Buttons: { path: "/components/buttons" },
    // Forms: { path: "/components/forms" },
    // Modals: { path: "/components/modals" },
    // Navs: { path: "/components/navs" },
    // Navbars: { path: "/components/navbars" },
    // Pagination: { path: "/components/pagination" },
    // Popovers: { path: "/components/popovers" },
    // Progress: { path: "/components/progress" },
    // Tables: { path: "/components/tables" },
    // Tabs: { path: "/components/tabs" },
    // Tooltips: { path: "/components/tooltips" },
    // Toasts: { path: "/components/toasts" },
    // WidgetsComponent: { path: "/components/widgets" }
};